Creada expectativa de que se debe poder acceder a los elementos de la matriz
Failures:

  1) Matriz Debe poder accederse a los elementos de la matriz
     Failure/Error: @matriz[0][0].should eq(1)
     NoMethodError:
       undefined method `[]' for #<Matriz:0x0000000215dcc0>
     # ./spec/matrices_spec.rb:13:in `block (2 levels) in <top (required)>'

Finished in 0.00126 seconds
2 examples, 1 failure

Failed examples:

rspec ./spec/matrices_spec.rb:12 # Matriz Debe poder accederse a los elementos de la matriz