Creada expectativa para la resta de dos matrices.
Failures:

  1) Matriz Debe restar dos matrices
     Failure/Error: @matriz3 = @matriz-@matriz2
     NoMethodError:
       undefined method `-' for #<Matriz:0x00000000fde1c0>
     # ./spec/matrices_spec.rb:39:in `block (2 levels) in <top (required)>'

Finished in 0.01531 seconds
4 examples, 1 failure

Failed examples:

rspec ./spec/matrices_spec.rb:38 # Matriz Debe restar dos matrices