Creada expectativa para la multiplicacion de dos matrices.
Failures:

  1) Matriz Debe multiplicar dos matrices
     Failure/Error: @matriz3 = @matriz*@matriz2
     NoMethodError:
       undefined method `*' for #<Matriz:0x000000012aa458>
     # ./spec/matrices_spec.rb:52:in `block (2 levels) in <top (required)>'

Finished in 0.01544 seconds
5 examples, 1 failure

Failed examples:

rspec ./spec/matrices_spec.rb:51 # Matriz Debe multiplicar dos matrices