Creada expectativa para la suma de dos matrices.
Failures:

  1) Matriz Debe sumar dos matrices
     Failure/Error: @matriz3 = @matriz+@matriz2
     NoMethodError:
       undefined method `+' for #<Matriz:0x0000000359b480>
     # ./spec/matrices_spec.rb:25:in `block (2 levels) in <top (required)>'

Finished in 0.00177 seconds
3 examples, 1 failure

Failed examples:

rspec ./spec/matrices_spec.rb:24 # Matriz Debe sumar dos matrices